import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '../components/Card/Card';
import CultureIcon from "../../public/culture-icon.svg";
import SporIcon from "../../public/sport-icon.svg";
import EntertaimentIcon from "../../public/entertaiment-icon.svg";
import DeveloperIcon from "../../public/developer-icon.svg";
import MainImage from "../../public/QandA.png";
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });
const cards = [
  { to: "generalculture", text: "Cultura General", icon: CultureIcon },
  { to: "sports", text: "Deportes", icon: SporIcon },
  { to: "entertaiment", text: "Entretenimiento", icon: EntertaimentIcon },
  { to: "developer", text: "Conceptos de Programación", icon: DeveloperIcon },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>RespondeME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.imageandp}>
        <Image src={MainImage} alt="Imagen repressentativa de RespondeME" className={styles.image}/>
        <p className={styles.paragraph}>
          ¡Bienvenido/a a nuestro juego de preguntas y respuestas RespondeME! 
          En RespondeME, encontrarás preguntas sobre diversas categorías, como Cultura General, Conceptos de Programación, 
          Deportes y Entretenimiento. 
          ¡Que disfrutes jugando en RespondeME y buena suerte!
        </p>
        </section>
        <section className={styles.cards}>
          { cards.map(el => <Card
                              key={el.text}
                              text={el.text}
                              icon={el.icon}
                              to={el.to}/>) }
        </section>
      </main>
    </>
  )
}
