import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '../components/Card/Card';
import CultureIcon from "../../public/culture-icon.svg";
import SporIcon from "../../public/sport-icon.svg";
import EntertaimentIcon from "../../public/entertaiment-icon.svg";
import DeveloperIcon from "../../public/developer-icon.svg";

const inter = Inter({ subsets: ['latin'] });
const cards = [
  { to: "generalculture", text: "Cultura General", icon: CultureIcon },
  { to: "sports", text: "Deportes", icon: SporIcon },
  { to: "entertaiment", text: "Entretenimiento", icon: EntertaimentIcon },
  { to: "developer", text: "Conceptos de Programación", icon: DeveloperIcon },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>RespondeME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>¡Bienvenido/a a nuestro juego de preguntas y respuestas RespondeME! 
          Tienes solo 10 segundos para responder cada pregunta y demostrar tu habilidad. ¡Que comience la diversión!
          En RespondeME, encontrarás preguntas sobre diversas categorías, como Cultura General, Conceptos de Programación, 
          Deportes y Entretenimiento. 
          Prepárate para poner a prueba tus conocimientos y aprender cosas nuevas.
          ¡Que disfrutes jugando en RespondeME y buena suerte!</p>
        <section className={styles.cards}>
          { cards.map(el => <Card
                              key={el.text}
                              text={el.text}
                              icon={el.icon}
                              to={el.to}/>) }
        </section>
      </main>
    </>
  )
}
